name: 버그 신고
description: 봇에 대한 버그를 신고합니다.
title: "[버그]: "
labels: [버그]
body:
  - type: markdown
    attributes:
      value: |
        버그를 제보해주셔서 감사드립니다. 아래의 빈칸에 해당하는 내용을 채워주세요!
  - type: input
    id: bug_point
    attributes:
      label: 어느 명령어에서 버그가 발생하나요?
      description: 해당 버그가 발생하는 병령어/기능 을 알려주세요!
    validations:
      required: true
  - type: textarea
    id: bug_context
    attributes:
      label: 어떤 버그가 발생하나요?
      description: 발생하는 버그에 대해 자세히 적어주세요.
    validations:
      required: true
  - type: textarea
    id: if_no_bug
    attributes:
      label: 원래는 어떻게 작동해야했나요?
      description: 만약, 버그가 발생하지 않았더라면, 이 명령어/기능 은 어떻게 작동해야 했나요?
    validations:
      required: true
  - type: checkboxes
    id: platform_device
    attributes:
      label: 이 버그가 발생한 기기는 무었인가요?
      description: 해당되는 기기를 선택해주세요.
      options:
        - label: PC (컴퓨터)
        - label: Mobile (휴대폰)
        - label: Web (웹버전)
  - type: input
    id: platform_ver
    attributes:
      label: 디스코드 버전
      description: 사용하고 계시는 디스코드의 버전을 알려주세요!
    validations:
      required: true

