name: 오타/맞춤법 신고
description: 봇의 명령어, 도움말 페이지 등 술팽봇과 관련된 서비스의 오타/문법상의 오류를 신고합니다.
title: "[오타]: "
labels: [오타]
body:
  - type: markdown
    attributes:
      value: |
        오타/맞춤법오류 를 제보해주셔서 감사드립니다. 아래의 빈칸에 해당하는 내용을 채워주세요!
  - type: input
    id: typo_point
    attributes:
      label: 어느 명령어/페이지 에서 버그가 발생하나요?
      description: 해당 버그가 발생하는 명령어/페이지 를 알려주세요!
    validations:
      required: true
  - type: textarea
    id: bug_context
    attributes:
      label: 어떤 문제인가요?
      description: 해당 문제에 대해서 자세히 설명해주세요! (사진을 넣으면 더 좋아요!)
    validations:
      required: true
